### ISSUE TITLE
CI on Windows failing... again

### ISSUE THREAD

**Issue by DE0CH** [auto-optimization/iracepy#23] opened 2022-12-13 17:01 UTC
This time it seems to be caused by either github or actions/setup-r-dependencies ...

```
   Error: 
  ! error in pak subprocess
  Caused by error in `pkgs$platform[winbin] <- ifelse(is.na(archs) | archs %in% c("i386,x64", …`:
  ! replacement has length zero
```

Seems like it was trying to get the platform, but the code is somehow buggy or the platform didn't return the right string?  

AHHHHHH WHYYYYYY

**Comment by MLopez-Ibanez** [comment] 2022-12-14 14:02
> AHHHHHH WHYYYYYY

Hi @DE0CH Is getting this working crucial for what you are trying to achieve with the surrogates project? If not, I would not worry too much about it for now. `iracepy` should be a tool to achieve something, it is not the goal itself.

**Comment by MLopez-Ibanez** [comment] 2022-12-14 14:24
Fixed but also opened https://github.com/r-lib/pak/issues/448

**Comment by MLopez-Ibanez** [comment] 2022-12-14 14:42
spoke too fast. The problem is caused by the present of the cache. Removing the cache fixes it, but it will fail again in the next run... oh well, let's see what the `pak` devs say. It may be a `r-lib/actions` bug.

**Comment by MLopez-Ibanez** [comment] 2022-12-14 16:37
OK, the problem is the cache, so I have disabled it. Once the bug is fixed by `pak` we can re-enable it.

**Closed as completed by MLopez-Ibanez** 2022-12-14 16:37 UTC
